# src/fraud_scorer/config/pipeline_config.yaml
pipeline:
  isolation_level: strict
  batch_size: 3
  parallel_workers: 2
  memory_limits:
    factura: 50
    factura_compra: 50
    poliza: 30
    poliza_seguro: 30
    denuncia: 100
    bitacora_gps: 200
    default: 50
  
consolidation:
  strategy: priority
  field_priorities:
    numero_poliza:
      - poliza
      - poliza_seguro
      - carta_reclamacion
    nombre_asegurado:
      - poliza
      - poliza_seguro
      - denuncia
    vigencia_inicio:  # ⚠️ Corregido
      - poliza
      - poliza_seguro
    vigencia_fin:     # ⚠️ Corregido
      - poliza
      - poliza_seguro
    domicilio_poliza: # ⚠️ Agregado
      - poliza
      - poliza_seguro
    fecha_ocurrencia:
      - denuncia
      - peritaje
      - carta_porte
    lugar_hechos:
      - denuncia
      - bitacora_gps
    monto_reclamacion:
      - factura
      - factura_compra
      - peritaje
    bien_reclamado:
      - factura
      - factura_compra
      - carta_porte